language: node_js
node_js:
  - 12

script:
  - npm run test -- --verbose

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: frolov.cyrill@gmail.com
  api_key:
    secure: 2x6fMEtUw9KIQekBlshrkmcCOKDfH52MJpmjmPq7/LjkRJtfCa5kdY/uUKH5uVGMohwNMD4iJBYDQABmgwwNuWSJuDy5je9pLWPZ8YG135mhYKyy3eF6GTJYXU5XIbwcm9MstVuxGV+RBTtdtYnujaOEO3qv0+02qyQmZ881Uo5ALNx0FyvDi7fXSz4vzrTn02wOlgqvEFfyP0In3ojUqjSjqtA26hkAOCACiqhYczvnI2ldpebAheCC3KSCdCvca1lj2+ozlbRYYEwa/HmyGOb9xrahX5OD0GTyZ38KMOaS6J1FQ+Vt5DVLJxOPmP8/9Hl9X/7gMVGC+yGRms3bR63GvLsRCRXblMAJYgowSv0ab89H0YfSEUD+8vu8dCSIvkb6qdeGIBLUpGZ8LSEV8B8S6melrPUcOOKRS4de6pppeOH175USFsHqPP0T0N8QEKbFdoEnubjpip4XQieZaCpW5FZ04itoCKFI3TrWc9YzNDxjwDhzIWu5cOF27DHKOU5XZat60bA0eUjOMYYDXaTGrRplG4UK11rHrlI15z6UggKuJ7t1rNSjPkyrG9/CbNqLuVWPtLWLe6A6RocjK6TAPT9cFDReq5UkGzGyIppfPhMj2/r4iRzhP4RpJsfAe5++hXEzTt1TFTl6b4BBSWSdPG5tqk9mVKzpOPdLW2E=
  on:
    branch: master
